@include('modal.success-register')
@include('modal.voucher-modal')
@include('modal.payment-successful')
@include('modal.chat')
@include('modal.reply')
@include('modal.noti-verify-email')
@include('modal.contact')
